In [12]:
import pandas as pd

df = pd.read_csv("Data/2017_Financial_Data.csv")
df.shape

(4960, 225)

In [13]:
df.head()

,Unnamed: 0,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,...,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2018 PRICE VAR [%],Class
0,PG,6.505800e+10,-0.0037,3.263800e+10,3.242000e+10,0.000000e+00,1.865400e+10,1.865400e+10,1.376600e+10,4.650000e+08,...,0.0505,-0.0195,-0.0529,0.0012,0.0325,0.0000,-0.0156,Consumer Defensive,4.975151,1
1,VIPS,1.102060e+10,0.3525,8.557810e+09,2.462794e+09,2.733452e+08,8.201852e+08,2.056136e+09,4.066575e+08,1.245995e+07,...,0.9219,0.4764,0.5889,1.5821,0.3805,0.2141,0.1920,Consumer Defensive,-56.320000,0
2,KR,1.153370e+11,0.0501,8.950200e+10,2.583500e+10,0.000000e+00,1.916200e+10,2.238300e+10,3.452000e+09,5.220000e+08,...,-0.0490,0.0637,0.0769,0.0071,0.1654,0.0000,0.0678,Consumer Defensive,-0.990449,0
3,RAD,2.292754e+10,0.1039,1.786283e+10,5.064707e+09,0.000000e+00,4.776995e+09,4.816124e+09,2.485830e+08,2.000650e+08,...,0.1063,-0.3365,0.0281,0.0502,-0.5295,0.0000,0.0427,Consumer Defensive,-66.666666,0
4,GIS,1.561980e+10,-0.0570,1.005200e+10,5.567800e+09,0.000000e+00,2.888800e+09,3.069200e+09,2.498600e+09,2.951000e+08,...,0.0509,0.0494,0.0046,-0.0943,0.1246,0.0000,-0.0738,Consumer Defensive,-31.280412,0

In [14]:
df.dtypes.value_counts()

float64    222
str          2
int64        1
Name: count, dtype: int64

In [15]:
df.isna().mean().sort_values(ascending=False).head(20)

operatingCycle                                0.998992
cashConversionCycle                           0.998992
shortTermCoverageRatios                       0.508065
10Y Shareholders Equity Growth (per Share)    0.473387
10Y Revenue Growth (per Share)                0.468145
10Y Net Income Growth (per Share)             0.468145
10Y Operating CF Growth (per Share)           0.465726
10Y Dividend per Share Growth (per Share)     0.458468
dividendPayoutRatio                           0.456452
priceEarningsToGrowthRatio                    0.456452
Net Debt to EBITDA                            0.443750
niperEBT                                      0.432460
effectiveTaxRate                              0.432460
nIperEBT                                      0.432460
eBTperEBIT                                    0.410484
ebtperEBIT                                    0.410484
Net Debt                                      0.393347
Other Assets                                  0.385282
priceCashFlowRatio                            0.372984
enterpriseValueMultiple                       0.362903
dtype: float64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.describe().T.sort_values("max", ascending=False).head(10)

,count,mean,std,min,25%,50%,75%,max
Market Cap,3953.0,3.280583e+10,1.530189e+12,0.000000e+00,225041845.0,1.019212e+09,4.231097e+09,9.619200e+13
Working Capital,3267.0,6.761247e+09,2.617860e+11,-4.282574e+12,8641196.5,9.097900e+07,3.977500e+08,1.235392e+13
Invested Capital,4125.0,1.748421e+10,1.168146e+11,-6.720000e+08,97226000.0,8.946710e+08,4.573558e+09,2.542702e+12
Total assets,4412.0,1.920714e+10,1.197433e+11,0.000000e+00,209642250.0,1.232828e+09,5.423116e+09,2.533600e+12
Tangible Asset Value,4145.0,1.550277e+10,1.034673e+11,-2.751015e+09,167031000.0,9.292740e+08,4.066400e+09,2.479208e+12
Total liabilities,4390.0,1.478702e+10,1.037279e+11,-6.750151e+09,78506750.0,6.677770e+08,3.561099e+09,2.277907e+12
Total current liabilities,4310.0,8.036507e+09,7.785797e+10,-2.096554e+10,30521000.0,1.859495e+08,1.070621e+09,1.967746e+12
Investments,4231.0,8.819431e+09,8.213332e+10,-5.208770e+08,0.0,1.253300e+07,3.806695e+08,1.886303e+12
Other Liabilities,4360.0,6.420738e+09,7.188645e+10,-8.306800e+10,7263750.0,6.572000e+07,4.913411e+08,1.781583e+12
Revenue,4435.0,5.085608e+09,3.148389e+10,-3.004500e+07,59000000.0,4.400000e+08,2.254111e+09,1.695864e+12

In [18]:
df.columns.tolist()

['Unnamed: 0',
 'Revenue',
 'Revenue Growth',
 'Cost of Revenue',
 'Gross Profit',
 'R&D Expenses',
 'SG&A Expense',
 'Operating Expenses',
 'Operating Income',
 'Interest Expense',
 'Earnings before Tax',
 'Income Tax Expense',
 'Net Income - Non-Controlling int',
 'Net Income - Discontinued ops',
 'Net Income',
 'Preferred Dividends',
 'Net Income Com',
 'EPS',
 'EPS Diluted',
 'Weighted Average Shs Out',
 'Weighted Average Shs Out (Dil)',
 'Dividend per Share',
 'Gross Margin',
 'EBITDA Margin',
 'EBIT Margin',
 'Profit Margin',
 'Free Cash Flow margin',
 'EBITDA',
 'EBIT',
 'Consolidated Income',
 'Earnings Before Tax Margin',
 'Net Profit Margin',
 'Cash and cash equivalents',
 'Short-term investments',
 'Cash and short-term investments',
 'Receivables',
 'Inventories',
 'Total current assets',
 'Property, Plant & Equipment Net',
 'Goodwill and Intangible Assets',
 'Long-term investments',
 'Tax assets',
 'Total non-current assets',
 'Total assets',
 'Payables',
 'Short-term debt',
 'Total current liabilities',
 'Long-term debt',
 'Total debt',
 'Deferred revenue',
 'Tax Liabilities',
 'Deposit Liabilities',
 'Total non-current liabilities',
 'Total liabilities',
 'Other comprehensive income',
 'Retained earnings (deficit)',
 'Total shareholders equity',
 'Investments',
 'Net Debt',
 'Other Assets',
 'Other Liabilities',
 'Depreciation & Amortization',
 'Stock-based compensation',
 'Operating Cash Flow',
 'Capital Expenditure',
 'Acquisitions and disposals',
 'Investment purchases and sales',
 'Investing Cash flow',
 'Issuance (repayment) of debt',
 'Issuance (buybacks) of shares',
 'Dividend payments',
 'Financing Cash Flow',
 'Effect of forex changes on cash',
 'Net cash flow / Change in cash',
 'Free Cash Flow',
 'Net Cash/Marketcap',
 'priceBookValueRatio',
 'priceToBookRatio',
 'priceToSalesRatio',
 'priceEarningsRatio',
 'priceToFreeCashFlowsRatio',
 'priceToOperatingCashFlowsRatio',
 'priceCashFlowRatio',
 'priceEarningsToGrowthRatio',
 'priceSalesRatio',
 'dividendYield',
 'enterpriseValueMultiple',
 'priceFairValue',
 'ebitperRevenue',
 'ebtperEBIT',
 'niperEBT',
 'grossProfitMargin',
 'operatingProfitMargin',
 'pretaxProfitMargin',
 'netProfitMargin',
 'effectiveTaxRate',
 'returnOnAssets',
 'returnOnEquity',
 'returnOnCapitalEmployed',
 'nIperEBT',
 'eBTperEBIT',
 'eBITperRevenue',
 'payablesTurnover',
 'inventoryTurnover',
 'fixedAssetTurnover',
 'assetTurnover',
 'currentRatio',
 'quickRatio',
 'cashRatio',
 'daysOfSalesOutstanding',
 'daysOfInventoryOutstanding',
 'operatingCycle',
 'daysOfPayablesOutstanding',
 'cashConversionCycle',
 'debtRatio',
 'debtEquityRatio',
 'longtermDebtToCapitalization',
 'totalDebtToCapitalization',
 'interestCoverage',
 'cashFlowToDebtRatio',
 'companyEquityMultiplier',
 'operatingCashFlowPerShare',
 'freeCashFlowPerShare',
 'cashPerShare',
 'payoutRatio',
 'operatingCashFlowSalesRatio',
 'freeCashFlowOperatingCashFlowRatio',
 'cashFlowCoverageRatios',
 'shortTermCoverageRatios',
 'capitalExpenditureCoverageRatios',
 'dividendpaidAndCapexCoverageRatios',
 'dividendPayoutRatio',
 'Revenue per Share',
 'Net Income per Share',
 'Operating Cash Flow per Share',
 'Free Cash Flow per Share',
 'Cash per Share',
 'Book Value per Share',
 'Tangible Book Value per Share',
 'Shareholders Equity per Share',
 'Interest Debt per Share',
 'Market Cap',
 'Enterprise Value',
 'PE ratio',
 'Price to Sales Ratio',
 'POCF ratio',
 'PFCF ratio',
 'PB ratio',
 'PTB ratio',
 'EV to Sales',
 'Enterprise Value over EBITDA',
 'EV to Operating cash flow',
 'EV to Free cash flow',
 'Earnings Yield',
 'Free Cash Flow Yield',
 'Debt to Equity',
 'Debt to Assets',
 'Net Debt to EBITDA',
 'Current ratio',
 'Interest Coverage',
 'Income Quality',
 'Dividend Yield',
 'Payout Ratio',
 'SG&A to Revenue',
 'R&D to Revenue',
 'Intangibles to Total Assets',
 'Capex to Operating Cash Flow',
 'Capex to Revenue',
 'Capex to Depreciation',
 'Stock-based compensation to Revenue',
 'Graham Number',
 'ROIC',
 'Return on Tangible Assets',
 'Graham Net-Net',
 'Working Capital',
 'Tangible Asset Value',
 'Net Current Asset Value',
 'Invested Capital',
 'Average Receivables',
 'Average Payables',
 'Average Inventory',
 'Days Sales Outstanding',
 'Days Payables Outstanding',
 'Days of Inventory on Hand',
 'Receivables Turnover',
 'Payables Turnover',
 'Inventory Turnover',
 'ROE',
 'Capex per Share',
 'Gross Profit Growth',
 'EBIT Growth',
 'Operating Income Growth',
 'Net Income Growth',
 'EPS Growth',
 'EPS Diluted Growth',
 'Weighted Average Shares Growth',
 'Weighted Average Shares Diluted Growth',
 'Dividends per Share Growth',
 'Operating Cash Flow growth',
 'Free Cash Flow growth',
 '10Y Revenue Growth (per Share)',
 '5Y Revenue Growth (per Share)',
 '3Y Revenue Growth (per Share)',
 '10Y Operating CF Growth (per Share)',
 '5Y Operating CF Growth (per Share)',
 '3Y Operating CF Growth (per Share)',
 '10Y Net Income Growth (per Share)',
 '5Y Net Income Growth (per Share)',
 '3Y Net Income Growth (per Share)',
 '10Y Shareholders Equity Growth (per Share)',
 '5Y Shareholders Equity Growth (per Share)',
 '3Y Shareholders Equity Growth (per Share)',
 '10Y Dividend per Share Growth (per Share)',
 '5Y Dividend per Share Growth (per Share)',
 '3Y Dividend per Share Growth (per Share)',
 'Receivables growth',
 'Inventory Growth',
 'Asset Growth',
 'Book Value per Share Growth',
 'Debt Growth',
 'R&D Expense Growth',
 'SG&A Expenses Growth',
 'Sector',
 '2018 PRICE VAR [%]',
 'Class']

In [19]:
df["Sector"].value_counts()

Sector
Financial Services        1247
Healthcare                 718
Technology                 665
Industrials                595
Consumer Cyclical          520
Basic Materials            282
Energy                     266
Real Estate                264
Consumer Defensive         199
Utilities                  110
Communication Services      94
Name: count, dtype: int64

In [20]:
df["2018 PRICE VAR [%]"].isna().sum()

np.int64(0)

In [21]:
pris = "2018 PRICE VAR [%]"
median = df[pris].median()
df["Target"] = (df[pris] > median).astype(int)
df["Target"].value_counts(normalize=True)

C:\Users\User\AppData\Local\Temp\ipykernel_20204\3594614472.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["Target"] = (df[pris] > median).astype(int)

Target
1    0.5
0    0.5
Name: proportion, dtype: float64

- 4 960 rader, 225 kolumner
- 0 dubbletter
- Över 50 % saknade värden i operatingCycle, cashConversionCycle, shortTermCoverageRatios
- Första kolumnen (Unnamed: 0) innehåller bolagens börskoder
- Sector har 11 branscher utan saknade värden
- "2018 PRICE VAR [%]" saknar inga värden
- Skapat Target (1 = över medianen, 0 = under), som är 50/50